modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
[[mods]]
modId="wawa"
version="${file.jarVersion}"
displayName="Wawa Mod"
logoFile="wawa.png"
credits=""
authors="fexlar"
description='''Adds Wawa chain store and Wawa cat inside of the game.'''
[[dependencies.wawa]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wawa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
